version: "3.8"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"

  publisher:
    build: ./publisher
    ports:
      - "8000:8000"
    depends_on:
      - kafka

  subscriber_interesting:
    build: ./subscriber_interesting
    ports:
      - "8001:8000"
    depends_on:
      - kafka
      - mongo

  subscriber_not_interesting:
    build: ./subscriber_not_interesting
    ports:
      - "8002:8000"
    depends_on:
      - kafka
      - mongo